### ISSUE TITLE
bug(react-sidemenu): The "path" argument must be of type string

### ISSUE THREAD

**Issue by AntoninBeaufort** [ionic-team/starters#1139]
**Starter Type:** react
**Starter Template:** sidemenu

**Description:**
When start a fresh install (`ionic start echo-admin sidemenu --type=react`) of react sidemenu starter, this error append :
```
[react-scripts] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
[react-scripts]     at validateString (internal/validators.js:117:11)
[react-scripts]     at Object.join (path.js:375:7)
[react-scripts]     at noopServiceWorkerMiddleware (D:\echo-admin\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
[react-scripts]     at Layer.handle [as handle_request] (D:\echo-admin\node_modules\express\lib\router\layer.js:95:5)
[react-scripts]     at trim_prefix (D:\echo-admin\node_modules\express\lib\router\index.js:317:13)
[react-scripts]     at D:\echo-admin\node_modules\express\lib\router\index.js:284:7
[react-scripts]     at Function.process_params (D:\echo-admin\node_modules\express\lib\router\index.js:335:12)
[react-scripts]     at next (D:\echo-admin\node_modules\express\lib\router\index.js:275:10)
[react-scripts]     at launchEditorMiddleware (D:\echo-admin\node_modules\react-dev-utils\errorOverlayMiddleware.js:20:7)
[react-scripts]     at Layer.handle [as handle_request] (D:\echo-admin\node_modules\express\lib\router\layer.js:95:5)
[react-scripts]     at trim_prefix (D:\echo-admin\node_modules\express\lib\router\index.js:317:13)
[react-scripts]     at D:\echo-admin\node_modules\express\lib\router\index.js:284:7
[react-scripts]     at Function.process_params (D:\echo-admin\node_modules\express\lib\router\index.js:335:12)
[react-scripts]     at next (D:\echo-admin\node_modules\express\lib\router\index.js:275:10)
[react-scripts]     at handleWebpackInternalMiddleware (D:\echo-admin\node_modules\react-dev-utils\evalSourceMapMiddleware.js:42:7)
[react-scripts]     at Layer.handle [as handle_request] (D:\echo-admin\node_modules\express\lib\router\layer.js:95:5)
```

**My `ionic info`:**

```
Ionic:

   Ionic CLI       : 6.1.0 (C:\Users\anton\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 5.0.0

Capacitor:

   Capacitor CLI   : 1.5.0
   @capacitor/core : 1.5.0

Utility:

   cordova-res : 0.9.0
   native-run  : 0.3.0

System:

   NodeJS : v12.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.7
   OS     : Windows 10
```

**Other Information:**

**Comment by AntoninBeaufort** [comment]
My bad, this was already fixed by this : [https://github.com/ionic-team/starters/pull/1137](https://github.com/ionic-team/starters/pull/1137) and reported here : [https://github.com/ionic-team/ionic/issues/20503](https://github.com/ionic-team/ionic/issues/20503)

It's just not merged actually, I think it's important to merge it fast because all news Ionic React users will be facing an error and may leave Ionic.
