### ISSUE TITLE
Ionic AWS Starter - can't publish the app

### ISSUE THREAD

**Issue by Norkori** [ionic-team/starters#52]
I followed the instructions on Ionic AWS Starter and when running awsmobile publish iv got theese errors:
```
[15:49:46]  typescript: D:/developer/scrum/myapp2/src/pages/account/account.ts, line: 43
            Expected 2 arguments, but got 1.

      L42:  refreshAvatar() {
      L43:    Storage.get(this.userId + '/avatar')
      L44:      .then(url => this.avatarPhoto = url);

[15:49:46]  typescript: D:/developer/scrum/myapp2/src/pages/tasks/tasks.ts, line: 51
            Property 'query' does not exist on type 'void | DocumentClient'. Property 'query' does not exist on type
            'void'.

      L50:  this.db.getDocumentClient()
      L51:    .then(client => client.query(params).promise())
      L52:    .then(data => { this.items = data.Items; })

[15:49:46]  typescript: D:/developer/scrum/myapp2/src/pages/tasks/tasks.ts, line: 82
            Property 'put' does not exist on type 'void | DocumentClient'. Property 'put' does not exist on type 'void'.

      L81:  this.db.getDocumentClient()
      L82:    .then(client => client.put(params).promise())
      L83:    .then(data => this.refreshTasks())

[15:49:46]  typescript: D:/developer/scrum/myapp2/src/pages/tasks/tasks.ts, line: 98
            Property 'delete' does not exist on type 'void | DocumentClient'. Property 'delete' does not exist on type
            'void'.

      L97:  this.db.getDocumentClient()
      L98:    .then(client => client.delete(params).promise())
      L99:    .then(data => this.items.splice(index, 1))

[15:49:46]  ionic-app-script task: "build"
[15:49:46]  Error: Failed to transpile program
Error: Failed to transpile program
    at new BuildError (D:\Developer\scrum\myApp2\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at D:\Developer\scrum\myApp2\node_modules\@ionic\app-scripts\dist\transpile.js:159:20
    at new Promise (<anonymous>)
    at transpileWorker (D:\Developer\scrum\myApp2\node_modules\@ionic\app-scripts\dist\transpile.js:107:12)
    at Object.transpile (D:\Developer\scrum\myApp2\node_modules\@ionic\app-scripts\dist\transpile.js:64:12)
    at D:\Developer\scrum\myApp2\node_modules\@ionic\app-scripts\dist\build.js:109:82
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myApp2@0.0.1 build: `ionic-app-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myApp2@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by ChristopherBrand** [comment]
I'm getting the same response just running ``ionic serve`` did you ever figure out what was happening with this?

**Comment by beevelop** [comment]
I can verify this happening with the currently available Starter too. This seems to be caused by some changes to the `aws-amplify` library. It is possible to fix this issues by casting the affected types and some minor tweaks to function calls:
```js
// src/pages/account/account.ts:42 (additional param & casting)
  refreshAvatar() {
    Storage.get(this.userId + '/avatar', {})
      .then(url => this.avatarPhoto = (url as string));
  }

// src/pages/confirmSignIn/confirmSignIn.ts:24 (adding null param)
  confirm() {
    Auth.confirmSignIn(this.user, this.code, null)

// src/pages/tasks/tasks.ts:0,52,83,99
import { DocumentClient } from 'aws-sdk/clients/dynamodb';
.then(client => (client as DocumentClient).query(params).promise())
.then(client => (client as DocumentClient).put(params).promise())
.then(client => (client as DocumentClient).delete(params).promise())
``` 

I can put those changes into a PR, if someone could verify this is the correct way to go / handle those exceptions.

**Comment by mlynch** [comment]
Thanks for the info, we will look into this

**Comment by jatindera** [comment]
Any update on [Ionic AWS starter] - ionic serve from fresh install returns errors. #88. ?
It seems like issue still persists when using "ionic start projectname aws"
Changes suggested by beevelop works though what is the plan to update the template ?
Thanks in advance.

**Comment by esstein** [comment]
It needs to manually install : 

> npm install @types/zen-observable
> npm install @types/paho-mqtt
