### ISSUE TITLE
ionic-cli commands breaks on starter templates

### ISSUE THREAD

**Issue by reajuria** [ionic-team/starters#941]
**Starter Type:** angular
**Starter Template:** blank, tabs (both)

**Description:**

I have issues while running ionic-cli commands like generate, serve, build on a newly created project. I post this issue as I currently have multiple projects on my setup and they're working fine (either angular 7, 8 and ionic 3, 4 (Most of them migrated from ionic v3 to @ionic/angular 4.6.2)). Getting ionic-cli errors like:
```
C:\Users\reaju\Projects\com-intecliag\project>ionic g component CodeDisplay
> ng.cmd generate component CodeDisplay
An unhandled exception occurred: Could not find module "@ionic/angular-toolkit" from "C:\\Users\\reaju\\Projects\\com-intecliag\\project\\".
See "C:\Users\reaju\AppData\Local\Temp\ng-jS3cXl\angular-errors.log" for further details.
[ERROR] Could not generate component.
```

**My `ionic info`:**

```
[ERROR] Error loading @ionic/angular-toolkit package.json: Error: Cannot find module '@ionic/angular-toolkit/package'
[ERROR] Error loading @angular/cli package.json: Error: Cannot find module '@angular/cli/package'
[ERROR] Error loading @angular-devkit/build-angular package.json: Error: Cannot find module
        '@angular-devkit/build-angular/package'
[ERROR] Error loading @angular-devkit/schematics package.json: Error: Cannot find module
        '@angular-devkit/schematics/package'

Ionic:

   Ionic CLI                     : 5.4.1 (C:\Users\reaju\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.9.1
   @angular-devkit/build-angular : not installed
   @angular-devkit/schematics    : not installed
   @angular/cli                  : not installed
   @ionic/angular-toolkit        : not installed

Cordova:

   Cordova CLI       : not installed
   Cordova Platforms : none
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm    : 6.9.0
   OS     : Windows 10
```

**Other Information:**

Installing 'missing' packages (@ionic/angular-toolkit, @angular/...) on global resolves the issue...

**C:\Users\reaju\AppData\Local\Temp\ng-jS3cXl\angular-errors.log**
```
[error] Error: Could not find module "@ionic/angular-toolkit" from "C:\\Users\\reaju\\Projects\\com-intecliag\\project".
    at Object.resolve (C:\Users\reaju\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\core\node\resolve.js:151:11)
    at NodeModulesEngineHost._resolvePackageJson (C:\Users\reaju\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:28:21)
    at NodeModulesEngineHost._resolveCollectionPath (C:\Users\reaju\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:69:40)
    at NodeModulesEngineHost.createCollectionDescription (C:\Users\reaju\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\file-system-engine-host-base.js:115:27)
    at SchematicEngine._createCollectionDescription (C:\Users\reaju\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\src\engine\engine.js:147:40)
    at SchematicEngine.createCollection (C:\Users\reaju\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\src\engine\engine.js:140:43)
    at GenerateCommand.getCollection (C:\Users\reaju\AppData\Roaming\npm\node_modules\@angular\cli\models\schematic-command.js:128:35)
    at GenerateCommand.initialize (C:\Users\reaju\AppData\Roaming\npm\node_modules\@angular\cli\models\schematic-command.js:44:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
```

**Node Modules dir**
```
C:\Users\reaju\Projects\com-intecliag\project\node_modules>dir
 Volume in drive C is OS
 Volume Serial Number is ...

 Directory of C:\Users\reaju\Projects\com-intecliag\project\node_modules

09/22/2019  09:36 PM    <DIR>          .
09/22/2019  09:36 PM    <DIR>          ..
09/22/2019  09:36 PM    <DIR>          @angular
09/22/2019  09:36 PM    <DIR>          @ionic
09/22/2019  09:36 PM    <DIR>          @ionic-native
09/22/2019  09:36 PM    <DIR>          @types
09/22/2019  09:36 PM    <DIR>          core-js
09/22/2019  09:36 PM    <DIR>          ionicons
09/22/2019  09:36 PM    <DIR>          rxjs
09/22/2019  09:36 PM    <DIR>          tslib
09/22/2019  09:36 PM    <DIR>          zone.js
```

**Angular Version on Dir**
```
C:\Users\reaju\Projects\com-intecliag\project>ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 8.3.5
Node: 10.16.3
OS: win32 x64
Angular: 8.1.3
... common, compiler, core, forms, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.803.5 (cli-only)
@angular-devkit/build-angular   <error>
@angular-devkit/core            8.3.5 (cli-only)
@angular-devkit/schematics      8.3.5 (cli-only)
@angular/cli                    <error>
@angular/compiler-cli           <error>
@angular/language-service       <error>
@schematics/angular             8.3.5 (cli-only)
@schematics/update              0.803.5 (cli-only)
rxjs                            6.5.3
typescript                      <error>
```

**Comment by reajuria** [comment]
My bad, never mind, I had NODE_ENV set to production. Just figured it out because Ionic Support Team asked me to do `npm ls -g @ionic/angular-toolkit`, Thank you!
